/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/{network}/tip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tip */
        get: operations["get_tip_api_v1__network__tip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocks */
        get: operations["list_blocks_api_v1__network__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/block/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Block */
        get: operations["get_block_api_v1__network__block__block_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/block/{block_id}/txs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Block Txs */
        get: operations["get_block_txs_api_v1__network__block__block_id__txs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/tx/{txid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tx */
        get: operations["get_tx_api_v1__network__tx__txid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/address/{addr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Address */
        get: operations["get_address_api_v1__network__address__addr__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/address/{addr}/txs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Address Txs */
        get: operations["get_address_txs_api_v1__network__address__addr__txs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/mempool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mempool */
        get: operations["get_mempool_api_v1__network__mempool_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/mempool/txs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mempool Txs */
        get: operations["get_mempool_txs_api_v1__network__mempool_txs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/mweb/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mweb Summary */
        get: operations["get_mweb_summary_api_v1__network__mweb_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/stats/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Charts */
        get: operations["get_charts_api_v1__network__stats_charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/search/{q}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1__network__search__q__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{network}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Network Events */
        get: operations["network_events_api_v1__network__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressStatsResponse */
        AddressStatsResponse: {
            /** Address */
            address: string;
            /** Balance */
            balance: string;
            /** Received */
            received: string;
            /** Sent */
            sent: string;
            /** Tx Count */
            tx_count: number;
            /** First Seen Height */
            first_seen_height: number;
            /** Last Seen Height */
            last_seen_height: number;
        };
        /** AddressTxItem */
        AddressTxItem: {
            /** Txid */
            txid: string;
            /** Block Height */
            block_height: number;
            /** Time */
            time: number;
            /** Delta */
            delta: string;
            /** Is Hogex */
            is_hogex: boolean;
            /** Has Mweb */
            has_mweb: boolean;
        };
        /** AddressTxPage */
        AddressTxPage: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Txs */
            txs: components["schemas"]["AddressTxItem"][];
        };
        /** BlockDetail */
        BlockDetail: {
            /** Height */
            height: number;
            /** Hash */
            hash: string;
            /** Prev Hash */
            prev_hash: string;
            /** Next Hash */
            next_hash: string | null;
            /** Time */
            time: number;
            /** Version */
            version: number | null;
            /** Bits */
            bits: string | null;
            /** Nonce */
            nonce: number | null;
            /** Size */
            size: number | null;
            /** Weight */
            weight: number | null;
            /** Difficulty */
            difficulty: string | null;
            /** Tx Count */
            tx_count: number;
            /** Total Out */
            total_out: string;
            /** Fees */
            fees: string;
            mweb: components["schemas"]["MwebBlockInfo"] | null;
        };
        /** BlockSummary */
        BlockSummary: {
            /** Height */
            height: number;
            /** Hash */
            hash: string;
            /** Time */
            time: number;
            /** Tx Count */
            tx_count: number;
            /** Size */
            size: number | null;
            /** Total Out */
            total_out: string;
            /** Fees */
            fees: string;
            /** Has Mweb */
            has_mweb: boolean;
        };
        /** BlockTxPage */
        BlockTxPage: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Txs */
            txs: components["schemas"]["TxSummary"][];
        };
        /** ChartPoint */
        ChartPoint: {
            /** Height */
            height: number;
            /** Time */
            time: number;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Networks */
            networks: {
                [key: string]: components["schemas"]["NetworkHealth"];
            };
        };
        /** MempoolInfo */
        MempoolInfo: {
            /** Count */
            count: number;
            /** Vsize */
            vsize: number;
            /** Total Fee */
            total_fee: string;
        };
        /** MempoolTxItem */
        MempoolTxItem: {
            /** Txid */
            txid: string;
            /** Has Mweb */
            has_mweb: boolean;
            /**
             * Is Hogex
             * @default false
             */
            is_hogex?: boolean;
        };
        /** MempoolTxids */
        MempoolTxids: {
            /** Txids */
            txids: string[];
            /** Txs */
            txs: components["schemas"]["MempoolTxItem"][];
        };
        /** MwebBlockInfo */
        MwebBlockInfo: {
            /** Height */
            height: number;
            /** Hash */
            hash: string;
            /** Kernel Offset */
            kernel_offset: string | null;
            /** Stealth Offset */
            stealth_offset: string | null;
            /** Num Kernels */
            num_kernels: number;
            /** Num Txos */
            num_txos: number;
            /** Kernel Root */
            kernel_root: string | null;
            /** Output Root */
            output_root: string | null;
            /** Leaf Root */
            leaf_root: string | null;
            /** Mweb Amount */
            mweb_amount: string;
            /** Pegin */
            pegin: string;
            /** Pegout */
            pegout: string;
            /** Kernel Fees */
            kernel_fees: string;
            /** Hogex Txid */
            hogex_txid: string | null;
        };
        /** MwebSummary */
        MwebSummary: {
            /** Mweb Amount */
            mweb_amount: string;
            /** Activation Height */
            activation_height: number;
            latest: components["schemas"]["MwebBlockInfo"] | null;
            /** Pegin 24H */
            pegin_24h: string;
            /** Pegout 24H */
            pegout_24h: string;
        };
        /** NetworkHealth */
        NetworkHealth: {
            /** Db Height */
            db_height: number;
            /** Node Height */
            node_height: number;
            /** Node Headers */
            node_headers: number;
            /** Ibd */
            ibd: boolean;
            /** Lag */
            lag: number;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Type
             * @enum {string}
             */
            type: "block" | "tx" | "address";
            /** Id */
            id: string;
        };
        /** TipResponse */
        TipResponse: {
            /** Height */
            height: number;
            /** Hash */
            hash: string;
            /** Time */
            time: number;
        };
        /** TxDetail */
        TxDetail: {
            /** Txid */
            txid: string;
            /** Hash */
            hash?: string | null;
            /** Version */
            version?: number | null;
            /** Size */
            size?: number | null;
            /** Vsize */
            vsize?: number | null;
            /** Weight */
            weight?: number | null;
            /** Locktime */
            locktime?: number | null;
            /** Vin */
            vin: components["schemas"]["TxVin"][];
            /** Vout */
            vout: components["schemas"]["TxVout"][];
            /** Hex */
            hex?: string | null;
            /** Blockhash */
            blockhash?: string | null;
            /** Block Height */
            block_height?: number | null;
            /** Idx */
            idx?: number | null;
            /** Fee */
            fee?: string | null;
            /** Is Hogex */
            is_hogex?: boolean | null;
            /** Has Mweb */
            has_mweb: boolean;
            /** Confirmations */
            confirmations: number;
            /** Time */
            time?: number | null;
            /** Blocktime */
            blocktime?: number | null;
        };
        /** TxSummary */
        TxSummary: {
            /** Txid */
            txid: string;
            /** Idx */
            idx: number;
            /** Fee */
            fee: string;
            /** Size */
            size: number | null;
            /** Total Out */
            total_out: string;
            /** Is Hogex */
            is_hogex: boolean;
            /** Has Mweb */
            has_mweb: boolean;
        };
        /** TxVin */
        TxVin: {
            /** Txid */
            txid?: string | null;
            /** Vout */
            vout?: number | null;
            /** Coinbase */
            coinbase?: string | null;
            /** Scriptsig */
            scriptSig?: {
                [key: string]: unknown;
            } | null;
            /** Sequence */
            sequence?: number | null;
            /** Txinwitness */
            txinwitness?: string[] | null;
            /** Ismweb */
            ismweb?: boolean | null;
            prevout?: components["schemas"]["TxVinPrevout"] | null;
        } & {
            [key: string]: unknown;
        };
        /** TxVinPrevout */
        TxVinPrevout: {
            /** Address */
            address: string | null;
            /** Value */
            value: string | null;
        };
        /** TxVout */
        TxVout: {
            /** N */
            n: number;
            /** Value */
            value?: string | null;
            /** Scriptpubkey */
            scriptPubKey?: {
                [key: string]: unknown;
            } | null;
            /** Ismweb */
            ismweb?: boolean | null;
            /** Spent By Txid */
            spent_by_txid?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_tip_api_v1__network__tip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocks_api_v1__network__blocks_get: {
        parameters: {
            query?: {
                before?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_api_v1__network__block__block_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_block_txs_api_v1__network__block__block_id__txs_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                block_id: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockTxPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tx_api_v1__network__tx__txid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txid: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TxDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_address_api_v1__network__address__addr__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addr: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_address_txs_api_v1__network__address__addr__txs_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                addr: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressTxPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mempool_api_v1__network__mempool_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MempoolInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mempool_txs_api_v1__network__mempool_txs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MempoolTxids"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mweb_summary_api_v1__network__mweb_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MwebSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_charts_api_v1__network__stats_charts_get: {
        parameters: {
            query: {
                metric: "difficulty" | "tx_count" | "fees" | "mweb_amount";
                from: number;
                to: number;
            };
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1__network__search__q__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                q: string;
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    network_events_api_v1__network__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                network: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
